### ISSUE TITLE
rforce binding raises undefined method error for invalid urls

### ISSUE THREAD

**Issue by desheikh** [undees/rforce#30]
with force 0.11 calling rforce binding with invalid url would raise a URI::InvalidURIError.

RForce::Binding.new('xxx', 'yyy').getUserInfo

This seems to have regressed in 0.12 and crashes with the error
undefined method `post2' for nil:NilClass.

**Comment by undees** [comment]
Thanks for reporting this!  v0.11 always attempted a connection first.  In v0.12, we moved that behavior to the two `login` methods.

I've modified `Binding` to attempt a connection before doing any remote calls.  Calling a remote method should now throw a bad URI or a refused connection, depending on what the invalid URI looks like.

**Comment by desheikh** [comment]
@undees, thanks for the quick fix, any chance you could do a point release for it?

**Comment by undees** [comment]
Done!

**Comment by desheikh** [comment]
:+1:  :)
